name: Deploy VPC

on:
  push:
    branches: [main]
    paths: ["envs/**", "modules/**"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, stage, prod]

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::713881823839:role/github-actions-oidc-role
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init
        working-directory: envs/${{ matrix.env }}


      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: envs/${{ matrix.env }}
